# Change these first
owner: Linkspring # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Linkspring
    url: https://lksg.me

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.lksg.me
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://cdn.lksg.me/static/img/logo/logo_shape.svg
  name: Linkspring Status
  introTitle: "Real-time status of Linkspring"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Help
      href: https://linkspring.freshdesk.com/support/home
    - title: Linkspring
      href: https://lksg.me

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
